# Generated by Django 5.1.2 on 2024-10-11 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'ASF', 'FLV', 'MKV', 'MOV'])])),
                ('description', models.TextField(blank=True, help_text='Video haqida qisqacha', null=True)),
            ],
        ),
    ]
